// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrqYdUGUJBw5zweJPGuJfHG04aFCbnsuE',
    appId: '1:453273668889:web:20b759415e429696bfc988',
    messagingSenderId: '453273668889',
    projectId: 'attendance-app-1833b',
    authDomain: 'attendance-app-1833b.firebaseapp.com',
    storageBucket: 'attendance-app-1833b.firebasestorage.app',
    measurementId: 'G-Y7PVYD9CR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA00GblfOFwWRyqAJpCP2ZVV6RnLQLrPC8',
    appId: '1:453273668889:android:b5821f2cbad940dabfc988',
    messagingSenderId: '453273668889',
    projectId: 'attendance-app-1833b',
    storageBucket: 'attendance-app-1833b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZCVqjP-DNX7xKIFPRVPJZlFpSmATwSV4',
    appId: '1:453273668889:ios:6f77fd49127a3d89bfc988',
    messagingSenderId: '453273668889',
    projectId: 'attendance-app-1833b',
    storageBucket: 'attendance-app-1833b.firebasestorage.app',
    androidClientId: '453273668889-2qduhp5t56dov2is3pk3cpio4fp2ife8.apps.googleusercontent.com',
    iosClientId: '453273668889-ld5mki3stfpigolodo5qti2ban9q0rpt.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZCVqjP-DNX7xKIFPRVPJZlFpSmATwSV4',
    appId: '1:453273668889:ios:6f77fd49127a3d89bfc988',
    messagingSenderId: '453273668889',
    projectId: 'attendance-app-1833b',
    storageBucket: 'attendance-app-1833b.firebasestorage.app',
    androidClientId: '453273668889-2qduhp5t56dov2is3pk3cpio4fp2ife8.apps.googleusercontent.com',
    iosClientId: '453273668889-ld5mki3stfpigolodo5qti2ban9q0rpt.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrqYdUGUJBw5zweJPGuJfHG04aFCbnsuE',
    appId: '1:453273668889:web:282f83ae562e2b90bfc988',
    messagingSenderId: '453273668889',
    projectId: 'attendance-app-1833b',
    authDomain: 'attendance-app-1833b.firebaseapp.com',
    storageBucket: 'attendance-app-1833b.firebasestorage.app',
    measurementId: 'G-0VHB9RSCGL',
  );
}
